version: '3.4'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
  demoapp:
    build:
      context: .
      dockerfile: Dockerfile-demoapp
    container_name: demoapp
    ports:
      - 8080:8080
  nginx-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx-prometheus/gateway.conf:/etc/nginx/conf.d/default.conf
      - nginx-logs:/var/log/nginx
    ports:
      - 9000:80
    container_name: nginx-proxy
  nginx-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter
    volumes:
      - ./nginx-prometheus/gateway.hcl:/etc/prometheus-nginxlog-exporter.hcl
      - nginx-logs:/var/log/nginx
    command: ["-config-file", "/etc/prometheus-nginxlog-exporter.hcl"]
    ports:
      - 4040:4040
    depends_on:
      - nginx-proxy

volumes:
  nginx-logs:
