FROM maven:3.6.3-jdk-8 as builder
WORKDIR /app
COPY ./src /app/src
COPY ./pom.xml /app
RUN mvn package

FROM openjdk:8
WORKDIR /app
COPY --from=builder /app/target/demo-0.0.1-SNAPSHOT-spring-boot.jar /app/demo-0.0.1-SNAPSHOT-spring-boot.jar
EXPOSE 8080
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/demo-0.0.1-SNAPSHOT-spring-boot.jar"]