apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    editable: true
    access: proxy
    url: http://prometheus:9090

  - name: CloudWatch
    type: cloudwatch
    editable: true
    jsonData:
      authType: keys
      defaultRegion: eu-central-1
    secureJsonData:
      accessKey: AKIAQ5SSLGXDU2TZ24K2
      secretKey: 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