apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    editable: true
    access: proxy
    url: http://prometheus:9090

  - name: CloudWatch
    type: cloudwatch
    editable: true
    jsonData:
      authType: keys
      defaultRegion: eu-central-1
    secureJsonData:
      accessKey: <your_access_key>
      secretKey: <your_secret_key>